from __future__ import annotations

from dataclasses import dataclass

import torch

from .sunsal import SunSAL, SunSALConfig

"""
Multilinear Mixing Model (MLM) implementation based on:

Heylen, R., & Scheunders, P. (2016)
A Multilinear Mixing Model for Nonlinear Spectral Unmixing.
IEEE TGRS, 54(1), 240-251.

Physical picture (Section III-A of the paper): a photon hitting the scene
interacts with at least one endmember; after every interaction it has
probability P of bouncing again and probability (1-P) of escaping to the
sensor, and which endmember it hits is proportional to that endmember's
abundance. Summing the contribution of every possible bounce sequence
(1, 2, 3, ... interactions), weighted by its probability, telescopes into a
single closed-form ratio (paper Eq. 14-15):

    x = (1 - P) * y / (1 - P * y),   y = sum_i a_i * w_i   (elementwise per band)

P=0 recovers the ordinary linear mixing model exactly. P in (0, 1) pulls the
reflectance below the linear mixture (extra absorption from extra bounces);
P<0 is not physically meaningful under the derivation above but is still a
valid point on the same curve, and pulls reflectance above the linear
mixture. This module deliberately allows P<0 (unlike the paper's headline
P<1 constrained-positive usage) because this project's own bilinear/GBM
synthetic generator (`core_math.mix_pixels`, `nonlinearity_gamma`) only ever
*adds* a positive term relative to the linear mixture (every per-pair
`gamma_ij` is drawn from `Uniform(0, nonlinearity_gamma)`, never negative) -
fitting MLM to that kind of data requires negative P, exactly as the paper's
own experiment (Section IV-A) found when unmixing Fan/GBM-generated data with
MLM.

The paper jointly fits abundances and P per pixel via constrained SQP
(MATLAB fmincon). To keep this implementation simple, we instead alternate
between two cheap sub-steps that reuse the project's existing SunSAL solver:

1. Fix the abundances (hence y = a @ endmembers) and grid-search the single
   scalar P that minimizes reconstruction error, vectorized over all pixels
   at once.
2. Fix P and observe that the model equation rearranges to a linear system
   in the abundances: y = x / (1 - P + P*x). So the (elementwise) transformed
   target x / (1 - P + P*x) can be fed straight back into SunSAL to refit the
   abundances under the usual ANC/ASC constraints.

Repeating this a few times approximates the paper's joint fit without a
general-purpose constrained nonlinear optimizer.

Verified (see conversation/scratch checks, not a committed test): on data
generated by this exact model, MLM recovers abundances far more accurately
than plain SunSAL. On data generated by `mix_pixels`'s GBM model,
however, MLM fits the pixel reconstruction better than SunSAL (lower
reconstruction error - it does have an extra free parameter) but recovers
abundances *worse* than plain linear SunSAL. That matches the paper's own
finding (Section IV-A): each nonlinear model tends to only outperform on data
generated by its own assumptions, not on another model's nonlinearity. Don't
expect MLM to beat SunSAL/VPGDU on abundance_rmse for `nonlinearity_gamma`
runs; its value here is as a differently-biased comparison point and as a
per-pixel nonlinearity-strength diagnostic (`P` estimates), not a drop-in
upgrade over the linear solvers on this project's synthetic generator.
"""


@dataclass(slots=True)
class MLMConfig:
    """Configuration for the MLM solver."""

    p_min: float = -5.0
    p_max: float = 0.999
    num_p_candidates: int = 201
    refine_iters: int = 3
    sunsal_mu: float = 0.05
    sunsal_max_iters: int = 300
    sunsal_tol: float = 1e-6
    verbose: bool = False


class MLM:
    """Multilinear Mixing Model solver (Heylen & Scheunders, 2016)."""

    def __init__(self, config: MLMConfig):
        """Store configuration and initialize per-pixel P history.

        Parameters
        ----------
        config : MLMConfig
            Solver configuration object.
        """

        self.cfg = config
        self.history: dict[str, list[float]] = {"p_mean": [], "p_std": []}

    def _sunsal_solve(self, endmembers: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """Fit abundances to ``target`` via the project's SunSAL solver (ANC + ASC)."""

        solver = SunSAL(
            SunSALConfig(
                μ=self.cfg.sunsal_mu,
                max_iters=self.cfg.sunsal_max_iters,
                tol=self.cfg.sunsal_tol,
            )
        )
        return solver.solve(endmembers, target)

    def _best_p(self, y: torch.Tensor, x: torch.Tensor) -> torch.Tensor:
        """Grid-search the per-pixel scalar P minimizing ``||x - (1-P)y/(1-Py)||^2``.

        Vectorized over every candidate P and every pixel at once, since P is
        the model's only nonlinear unknown (paper Eq. 15) and a coarse grid is
        cheap and robust compared to a general-purpose 1D optimizer.
        """

        p_candidates = torch.linspace(
            self.cfg.p_min, self.cfg.p_max, self.cfg.num_p_candidates, device=y.device, dtype=y.dtype
        )
        # Looped (rather than broadcast over all candidates at once) so memory stays
        # O(n_pixels * n_bands) instead of O(num_p_candidates * n_pixels * n_bands),
        # which was large enough to OOM at thousands of pixels.
        sse = torch.empty(self.cfg.num_p_candidates, y.shape[0], device=y.device, dtype=y.dtype)
        for i in range(self.cfg.num_p_candidates):
            p = p_candidates[i]
            denom = (1.0 - p * y).clamp_min(1e-6)
            predicted = (1.0 - p) * y / denom
            sse[i] = ((predicted - x) ** 2).sum(dim=1)
        best_idx = sse.argmin(dim=0)
        return p_candidates[best_idx]

    def solve(self, endmembers: torch.Tensor, pixels: torch.Tensor) -> torch.Tensor:
        """Solve abundances for pixels under the MLM model.

        Parameters
        ----------
        endmembers : torch.Tensor
            Endmember matrix with shape ``(n_endmembers, n_bands)``.
        pixels : torch.Tensor
            Pixel matrix with shape ``(n_pixels, n_bands)``.

        Returns
        -------
        torch.Tensor
            Estimated abundances with shape ``(n_pixels, n_endmembers)``.
        """

        abundances = self._sunsal_solve(endmembers, pixels)
        p = torch.zeros(pixels.shape[0], device=pixels.device, dtype=pixels.dtype)

        for _ in range(self.cfg.refine_iters):
            y = abundances @ endmembers
            p = self._best_p(y, pixels)
            denom = ((1.0 - p.unsqueeze(1)) + p.unsqueeze(1) * pixels).clamp_min(1e-6)
            transformed_target = pixels / denom
            abundances = self._sunsal_solve(endmembers, transformed_target)

            if self.cfg.verbose:
                print(f"MLM refine | P mean={p.mean().item():.4f} | P std={p.std().item():.4f}")

        self.history["p_mean"].append(float(p.mean().item()))
        self.history["p_std"].append(float(p.std().item()))
        self.p_ = p
        return abundances
